phdljr/one-click-recipe-front

- src/App.svelte
- src/pages/Order/OrderPage.svelte
> Feature/cart - OrderPage 기본 틀 완성

- src/pages/Order/OrderPage.svelte
> Feature/cart - 이메일 추가, 결제 버튼 생성

- src/App.svelte
- src/pages/Order/OrderDetailPage.svelte
- src/pages/Order/OrderListPage.svelte
> Feature/cart - 주문목록, 주문 상세 페이지 구현

- src/App.svelte
- src/pages/MainPage.svelte
- src/pages/user/MyPage.svelte
> Feature/user - mypage 생성

- src/App.svelte
- src/pages/recipe/RecipeAllPage.svelte
- src/pages/recipe/RecipeCreatePage.svelte
> Feature/recipe - 레시피 등록 기능 구현

- src/App.svelte
- src/pages/order/OrderDetailPage.svelte
- src/pages/order/OrderListPage.svelte
- src/pages/order/OrderPage.svelte
> Chore: 대소문자 규칙 설정

- package-lock.json
- package.json
- src/lib/validates/recipe-validate.js
- src/pages/recipe/RecipeAllPage.svelte
- src/pages/recipe/RecipeCreatePage.svelte
> Feat: 레시피 생성 UI 및 검증 로직 추가

- src/pages/recipe/RecipeCreatePage.svelte
> Feat: 레시피 생성 시, Food getAll API 호출

- src/App.svelte
- src/components/food/FoodCard.svelte
- src/components/pay/PayButton.svelte
- src/components/recipe/RecipeCard.svelte
- src/components/review/ReviewCard.svelte
- src/pages/food/FoodAllPage.svelte
- src/pages/like/LikeListPage.svelte
- src/pages/order/OrderDetailPage.svelte
- src/pages/order/OrderListPage.svelte
- src/pages/order/OrderPage.svelte
- src/pages/recipe/RecipeAllPage.svelte
- src/pages/recipe/RecipeCreatePage.svelte
- src/pages/recipe/RecipePage.svelte
- src/pages/user/MyPage.svelte
> Feature/like - 좋아요 생성,삭제,수정 기능 구현

- src/pages/recipe/RecipePage.svelte
- src/pages/user/MyPage.svelte
- 
-창선님이 수정해주신 댓글 기능에 css 부분을 수정하였습니다.
그리고 지금 보시면 브랜치 이름명 feature/recipelike 라고 되어있는데 브랜치 이름이랑은 관련이 없는 기능입니다!!!
그 레시피 좋아요는 지금 "규태" 님이 진행중이시고
저는 댓글 부분 마무리 한것입니다. 제가 브랜치를 옮겨놓고 했어야했는데 이건 제 실수에요ㅜㅜ!
-
> 레시피에 댓글, 별점 다는 기능 구현

- src/App.svelte
- src/lib/const/jwt.js
- src/lib/const/user-rols.js
- src/pages/food/FoodAllPage.svelte
- src/pages/kakaopay/ApprovalPaymentPage.svelte
- src/pages/order/OrderListPage.svelte
- src/pages/order/OrderPage.svelte
- src/pages/recipe/RecipeAllPage.svelte
- src/pages/user/MyPage.svelte
- src/routes/MainRouter.svelte
- src/routes/common/CommonRouter.svelte
- src/routes/guest/GuestRouter.svelte
- src/routes/login/AdminRouter.svelte
- src/routes/login/LoginRouter.svelte
- src/routes/login/UserRouter.svelte
- src/store/admin.js
> Feat: 유저 상태에 따른 Router 설정

- src/components/LogoutButton.svelte
- src/components/food/FoodCard.svelte
- src/components/recipe/RecipeCard.svelte
- src/components/review/ReviewCard.svelte
- src/pages/recipe/RecipeAllPage.svelte
- src/pages/user/LoginPage.svelte
- src/pages/user/SignUpPage.svelte
> Refactor/UI - 전반적인 UI 수정

- src/pages/recipe/RecipeCreatePage.svelte
> Refactor/UI - 사진 미리 보기 수정 및 폰트 UI 변경

- src/pages/recipe/RecipeCreatePage.svelte
> feature/multipartfile - 사진 파일 용량 제한

- package-lock.json
- package.json
- src/lib/validates/recipe-validate.js
- src/lib/validates/review-validate.js
- src/pages/order/OrderPage.svelte
- src/pages/recipe/RecipeCreatePage.svelte
- src/pages/recipe/RecipePage.svelte
> Feature/validation/review - 리뷰 등록 시 검증

- package-lock.json
- src/components/nav/NavDrawer.svelte
- src/components/recipe/RecipeCard.svelte
- src/components/recipe/RecipeFoods.svelte
- src/pages/MainPage.svelte
- src/pages/like/LikeListPage.svelte
- src/pages/recipe/RecipeAllPage.svelte
- src/pages/recipe/RecipeCreatePage.svelte
- src/pages/recipe/RecipePage.svelte
- src/pages/user/LoginPage.svelte
- src/pages/user/MyPage.svelte
- src/pages/user/SignUpPage.svelte
> Refactor/uiux - 배경 색상, 글씨 색상 변경

- package-lock.json
- package.json
- src/pages/recipe/RecipeAllPage.svelte
> Feat: 무한 스크롤 도입

- src/components/recipe/RecipeReviews.svelte
- src/lib/const/pagination-const.js
- src/pages/recipe/RecipeAllPage.svelte
- src/pages/recipe/RecipePage.svelte
> Feature/scroll - 리뷰 무한 스크롤 적용

- src/components/recipe/RecipeCard.svelte
- src/components/recipe/RecipeFoods.svelte
- src/components/review/ReviewCard.svelte
- src/pages/recipe/RecipeAllPage.svelte
- src/pages/recipe/RecipeCreatePage.svelte
- src/pages/recipe/RecipePage.svelte
- 
- 레시피 구독 기능 구현
- 이미지 조정 및 변경 필요
- 레시피 삭제 생성
-
> feature: 구독 기능 구현

- .env.development
- .env.production
- package-lock.json
- package.json
- src/lib/host.js
- src/lib/kakao/kakao-login.js
> Feat: 배포/개발 환경 변수 설정
